name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls
  Android:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v1

    - name: Android
      run: |
        nuget restore
        brew install --cask xamarin-android
        cd XamarinNavigationBlank.Android
        /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /verbosity:normal /t:Rebuild /p:Configuration=Debug
      

      
